apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Brewfile
  annotations:
    github.com/project-slug: yaakovgamliel/Brewfile
spec:
  type: other
  lifecycle: unknown
  owner: infrastructure
